flowchart LR
  FE_ALQ[Frontend Alquiler]
  ALQ_CTRL[AlquilerController]
  ALQ_SVC[ServicioAlquiler]
  ITEM_REPO[ItemRepository]
  SALDO_SVC[SaldoService]
  DB_CAT[(DB Catálogo)]
  DB_USR[(DB Usuarios)]

  FE_ALQ --> ALQ_CTRL --> ALQ_SVC
  ALQ_SVC --> ITEM_REPO --> DB_CAT
  ALQ_SVC --> SALDO_SVC --> DB_USR
